- name: GRAFANA | Upload configuration
  template:
     src: templates/grafana.ini.j2
     dest: /etc/grafana/grafana.ini
     mode: 0640
     owner: root
     group: grafana
  notify:
      - restart grafana server
