- name: GRAFANA | Install
  include: install.yml
  tags:
    - install

- name: GRAFANA | Configure
  include: configure.yml
  tags:
    - configure

- name: GRAFANA | Service
  include: service.yml
  tags:
    - service
